import {
  AlertCircle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Home,
  ImageIcon,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  Battery,
  BatteryMedium,
  BatteryLow,
  Timer,
  CalendarDays,
  Edit,
  CheckCircle2,
  Clock,
  Search,
  RotateCcw,
  PanelLeftClose,
  PanelLeftOpen,
  Bell,
  Info,
  LifeBuoy,
  Zap,
  ListFilter,
  Menu,
} from "lucide-react"

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  file: File,
  fileText: FileText,
  image: ImageIcon,
  highEnergy: Battery,
  mediumEnergy: BatteryMedium,
  lowEnergy: BatteryLow,
  timer: Timer,
  calendar: CalendarDays,
  edit: Edit,
  complete: CheckCircle2,
  clock: Clock,
  home: Home,
  search: Search,
  undo: RotateCcw,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  bell: Bell,
  info: Info,
  lifeBuoy: LifeBuoy,
  zap: Zap,
  list: ListFilter,
  menu: Menu,
}
